### ISSUE TITLE
The [Update Peripheral] button not responding to user input

### ISSUE THREAD

**Issue by MMooreGitHub** [AntonTheDev/ExtendaBLE#2]
I'm running iOS 11.4.1 on an iPhone 6s+

Thanks

**Comment by AntonTheDev** [comment]
are you trying the demo?

**Comment by AntonTheDev** [comment]
Also, do you have a central and a peripheral running? I believe there are flags in the view controller that can turn each type of device on and off

**Comment by MMooreGitHub** [comment]
Hi,
 Yes, I’m running the iOS demo.

**Comment by AntonTheDev** [comment]
There is a ControllerConfig Flag you can adjust to setup the interface in 

https://github.com/AntonTheDev/ExtendaBLE/blob/master/ExtendaBLE-Demo/Shared/ViewController.swift

You need to configure it to run 1 peripheral, and 1 central

**Comment by MMooreGitHub** [comment]
Ok, thank you.
